### ISSUE TITLE
King doesn't become inactive when they lose their crown

### ISSUE THREAD

**Issue by nmego** [pocc/bosspiles#6]
https://ibb.co/LZCb5bB

**Comment by pocc** [comment]
Do you mean the king isn't dropping? I made the king lose and they dropped expectedly.

**Comment by nmego** [comment]
The king does drop, but as you can see in the attached screenshot, the king doesn't become 'inactive' even though they've just lost a game.

**Comment by pocc** [comment]
I think I solved this, please confirm.
